# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c512ca8ca02da045ec8d4a193863e0f744930df65256891e199b28824499a8c4098a3ac10adc68e547dcdbdb33009ea22290fd3ff1ca2069a9c5c907561b31e9

test:
  secret_key_base: 4b05e853e1553b0fb0023fd2868ad9af5b244f1ef3387f070c77bd99208e8e178a3143a573a491597009c3023321c78d4f1d07bce3ed0105ad26140842edb89d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
